"""sync check

Revision ID: eca58508a8db
Revises: 54d4d63ff45d
Create Date: 2025-08-26 13:34:27.744066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca58508a8db'
down_revision: Union[str, Sequence[str], None] = '54d4d63ff45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spimex_trading_results', 'oil_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'delivery_basis_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'delivery_basis_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'delivery_type_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'volume',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'total',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'count',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('spimex_trading_results', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_spimex_trading_results_date'), 'spimex_trading_results', ['date'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_basis_id'), 'spimex_trading_results', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_type_id'), 'spimex_trading_results', ['delivery_type_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_oil_id'), 'spimex_trading_results', ['oil_id'], unique=False)
    op.create_index('ix_str_composite', 'spimex_trading_results', ['oil_id', 'delivery_type_id', 'delivery_basis_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_str_composite', table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_oil_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_type_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_basis_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_date'), table_name='spimex_trading_results')
    op.alter_column('spimex_trading_results', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'count',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'total',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'volume',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_type_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'delivery_basis_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('spimex_trading_results', 'oil_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
